project_urls:
    Project Site: https://elastix.lumc.nl/
    Bug Tracker: https://github.com/SuperElastix/elastix_napari/issues
    Source Code: https://github.com/SuperElastix/elastix_napari
    User Support: https://groups.google.com/g/elastix-imageregistration
