# Add labels from the EDAM Bioimaging ontology
labels:
  ontology: EDAM-BIOIMAGING:alpha06
  terms:
  - Rigid registration
  - Deformable registration
  - Affine registration
  - 2D image
  - 3D image
  - Image segmentation
  - Medical imaging
